name: build
run-name: Build ydcmd Docker image
on:
  push:
    branches:
      - 'master'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
            images: |
                ${{ secrets.DOCKERHUB_USERNAME }}/ydcmd
            tags: |
                type=raw,value=latest
                type=raw,value={{VERSION}}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            YDCMD_VERSION=$VERSION
