name: build
run-name: Build ydcmd Docker image
on:
  push:
    branches:
      - 'master'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}"
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ydcmd:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ydcmd:${{ steps.vars.outputs.tag }}

